layouts_dir: 'node_modules/abas-demo-site/dist'

package_name: React Keyed File Browser
package_github_url: https://github.com/ABASystems/react-keyed-file-browser
package_npm_url: https://www.npmjs.com/package/react-keyed-file-browser
